# Consistent market colour palette — used across every module.
# One named colour per ticker so CL is always blue, NG always red, etc.
market_colors <- c(
  CL  = "#2980b9",   # steel blue   – WTI Crude
  BRN = "#27ae60",   # emerald      – Brent Crude
  NG  = "#e74c3c",   # red          – Natural Gas
  HO  = "#e67e22",   # orange       – Heating Oil
  RB  = "#8e44ad",   # purple       – RBOB Gasoline
  HTT = "#d35400",   # burnt sienna – WTI Houston
  CMT = "#7f8c8d"    # grey         – US Treasuries
)

# Null-coalescing operator — used across modules for colour fallbacks.
`%||%` <- function(x, y) if (!is.null(x) && !is.na(x)) x else y

# Key macro events — used to annotate volatility and factor charts.
# Returns lists of plotly `shapes` and `annotations` for vertical event lines.
event_vlines <- function(date_range = NULL) {
  events <- list(
    list(date = as.Date("2008-09-15"), label = "Lehman Bros."),
    list(date = as.Date("2020-03-16"), label = "COVID-19"),
    list(date = as.Date("2022-02-24"), label = "Russia-Ukraine")
  )
  if (!is.null(date_range)) {
    events <- Filter(function(e) e$date >= date_range[1] & e$date <= date_range[2], events)
  }
  list(
    shapes = lapply(events, function(e) {
      list(type = "line",
           x0 = as.character(e$date), x1 = as.character(e$date),
           y0 = 0, y1 = 1, yref = "paper",
           line = list(color = "rgba(80,80,80,0.30)", dash = "dot", width = 1.2))
    }),
    annotations = lapply(events, function(e) {
      list(x = as.character(e$date), y = 0.97, yref = "paper",
           text = e$label, showarrow = FALSE,
           xanchor = "left", yanchor = "top",
           font = list(size = 9, color = "rgba(80,80,80,0.65)"),
           textangle = -90)
    })
  )
}

# Alert / reference-line colour — distinct from any market colour.
# Use this for regime thresholds, ±2σ lines, and other annotations so they
# don't visually collide with NG's red (#e74c3c).
alert_color <- "#c0392b"

#' Access files in the current app
#'
#' Wrapper around \code{system.file()} that points to files inside
#' the installed package (i.e. \code{inst/}).  Generated by Golem.
#'
#' @param ... Path components passed to \code{system.file()}.
#' @noRd
app_sys <- function(...) {
  system.file(..., package = "GolemAppProject")
}

#' Read App Config
#'
#' @param value Value to retrieve from the config file.
#' @param config Name of the configuration to use.
#' @param use_parent Whether to inherit parent configuration values.
#' @noRd
#' @importFrom config get
get_golem_config <- function(
    value,
    config  = Sys.getenv("GOLEM_CONFIG_ACTIVE", Sys.getenv("R_CONFIG_ACTIVE", "default")),
    use_parent = TRUE
) {
  config::get(
    value      = value,
    config     = config,
    file       = app_sys("golem-config.yml"),
    use_parent = use_parent
  )
}
