#' Access files in the current app
#'
#' Wrapper around \code{system.file()} that points to files inside
#' the installed package (i.e. \code{inst/}).  Generated by Golem.
#'
#' @param ... Path components passed to \code{system.file()}.
#' @noRd
app_sys <- function(...) {
  system.file(..., package = "Golem_App_Project")
}

#' Read App Config
#'
#' @param value Value to retrieve from the config file.
#' @param config Name of the configuration to use.
#' @param use_parent Whether to inherit parent configuration values.
#' @noRd
#' @importFrom config get
get_golem_config <- function(
    value,
    config  = Sys.getenv("GOLEM_CONFIG_ACTIVE", Sys.getenv("R_CONFIG_ACTIVE", "default")),
    use_parent = TRUE
) {
  config::get(
    value      = value,
    config     = config,
    file       = app_sys("golem-config.yml"),
    use_parent = use_parent
  )
}
