# Consistent market colour palette — used across every module.
# One named colour per ticker so CL is always blue, NG always red, etc.
market_colors <- c(
  CL  = "#2980b9",   # steel blue   – WTI Crude
  BRN = "#27ae60",   # emerald      – Brent Crude
  NG  = "#e74c3c",   # red          – Natural Gas
  HO  = "#e67e22",   # orange       – Heating Oil
  RB  = "#8e44ad",   # purple       – RBOB Gasoline
  HTT = "#d35400",   # burnt sienna – WTI Houston
  CMT = "#7f8c8d"    # grey         – US Treasuries
)

# Null-coalescing operator — used across modules for colour fallbacks.
`%||%` <- function(x, y) if (!is.null(x) && !is.na(x)) x else y

# Alert / reference-line colour — distinct from any market colour.
# Use this for regime thresholds, ±2σ lines, and other annotations so they
# don't visually collide with NG's red (#e74c3c).
alert_color <- "#c0392b"

#' Access files in the current app
#'
#' Wrapper around \code{system.file()} that points to files inside
#' the installed package (i.e. \code{inst/}).  Generated by Golem.
#'
#' @param ... Path components passed to \code{system.file()}.
#' @noRd
app_sys <- function(...) {
  system.file(..., package = "GolemAppProject")
}

#' Read App Config
#'
#' @param value Value to retrieve from the config file.
#' @param config Name of the configuration to use.
#' @param use_parent Whether to inherit parent configuration values.
#' @noRd
#' @importFrom config get
get_golem_config <- function(
    value,
    config  = Sys.getenv("GOLEM_CONFIG_ACTIVE", Sys.getenv("R_CONFIG_ACTIVE", "default")),
    use_parent = TRUE
) {
  config::get(
    value      = value,
    config     = config,
    file       = app_sys("golem-config.yml"),
    use_parent = use_parent
  )
}
