#' Load parsed RTL continuous futures data
#'
#' Reads from the bundled feather file (\code{inst/extdata/futures_data.feather})
#' generated by \code{data-raw/generate_data.R}.  Falls back to parsing
#' \code{RTL::dflong} live if the file is not found (e.g. before the feather
#' file has been generated for the first time).
#'
#' @return A tibble: \code{date} (Date), \code{market} (chr),
#'   \code{contract} (int), \code{value} (dbl).
#' @export
#' @importFrom arrow read_feather
#' @importFrom dplyr mutate filter select
fct_load_futures_data <- function() {
  path <- system.file("extdata", "futures_data.feather",
                      package = "Golem_App_Project")

  if (nzchar(path)) {
    return(arrow::read_feather(path))
  }

  # Fallback: parse live from RTL (used before feather file exists)
  message("futures_data.feather not found — loading live from RTL::dflong")
  df        <- RTL::dflong
  names(df) <- tolower(names(df))
  df |>
    dplyr::mutate(
      market   = sub("[0-9]+$", "", series),
      contract = as.integer(sub("^[A-Za-z]+", "", series)),
      date     = as.Date(date)
    ) |>
    dplyr::filter(!is.na(value), !is.na(contract)) |>
    dplyr::select(date, market, contract, value)
}


#' Load FRED Constant Maturity Treasury yield data
#'
#' Reads from the bundled feather file (\code{inst/extdata/cmt_data.feather})
#' generated by \code{data-raw/generate_data.R}.  Falls back to live FRED
#' fetching via \code{tidyquant::tq_get()} if the file is not found.
#'
#' @return A tibble: \code{date} (Date), \code{maturity_label} (chr),
#'   \code{maturity_years} (dbl), \code{value} (dbl, yield \%).
#' @export
#' @importFrom arrow read_feather
#' @importFrom dplyr mutate filter select rename bind_rows
#' @importFrom tidyquant tq_get
fct_load_cmt_data <- function() {
  path <- system.file("extdata", "cmt_data.feather",
                      package = "Golem_App_Project")

  if (nzchar(path)) {
    return(arrow::read_feather(path))
  }

  # Fallback: fetch live from FRED (slow — 11 HTTP requests)
  message("cmt_data.feather not found — fetching live from FRED")
  cmt_meta <- data.frame(
    ticker         = c("DGS1MO","DGS3MO","DGS6MO",
                       "DGS1","DGS2","DGS3","DGS5",
                       "DGS7","DGS10","DGS20","DGS30"),
    maturity_years = c(1/12, 3/12, 6/12, 1, 2, 3, 5, 7, 10, 20, 30),
    stringsAsFactors = FALSE
  )

  result <- tryCatch({
    rows <- lapply(seq_len(nrow(cmt_meta)), function(i) {
      tidyquant::tq_get(cmt_meta$ticker[i], get = "economic.data") |>
        dplyr::rename(value = price) |>
        dplyr::mutate(
          maturity_label = cmt_meta$ticker[i],
          maturity_years = cmt_meta$maturity_years[i],
          date           = as.Date(date)
        ) |>
        dplyr::select(date, maturity_label, maturity_years, value)
    })
    dplyr::bind_rows(rows) |> dplyr::filter(!is.na(value))
  }, error = function(e) {
    warning("Could not fetch CMT data from FRED: ", conditionMessage(e))
    NULL
  })

  result
}
